# Generated by Django 4.0.1 on 2022-02-14 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('type', models.CharField(choices=[('Online', 'Пользователь входил в сайт'), ('Offline', 'Пользователь выходил из сайта')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
