# Generated by Django 4.0.1 on 2022-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useractivites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivites',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
