# Generated by Django 4.0.1 on 2022-02-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useractivites_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_people',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL),
        ),
    ]
