# Generated by Django 4.0.1 on 2022-02-19 21:28

import advertising.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, verbose_name=advertising.models.NearPlace)),
                ('flows', models.TextField(blank=True, null=True)),
                ('desription', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('zoom', models.FloatField()),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='#0077c2', max_length=10, null=True)),
                ('icon_text', models.CharField(blank=True, default='apartment', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Тип рекламы',
                'verbose_name_plural': 'Типы рекламов',
            },
        ),
        migrations.CreateModel(
            name='NearPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('advertising', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='advertising.advertising')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertising-images/')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertising.advertising')),
            ],
            options={
                'verbose_name': 'Фото Реклама',
                'verbose_name_plural': 'Фотки Реклама',
            },
        ),
        migrations.AddField(
            model_name='advertising',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to='advertising.advertisingtype'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
