# Generated by Django 4.0.1 on 2022-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
