# Generated by Django 4.0 on 2022-01-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_advertising_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='zoom',
            field=models.FloatField(),
        ),
    ]
