# Generated by Django 4.0.1 on 2022-02-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0002_advertising_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisingrent',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AddField(
            model_name='advertisingrent',
            name='organization_phone',
            field=models.CharField(default=888, max_length=255, verbose_name='Телефон организаций'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertising',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='desription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='flows',
            field=models.TextField(blank=True, null=True, verbose_name='Дорожные потоки'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='lat',
            field=models.FloatField(verbose_name='Lat местоположение'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='lng',
            field=models.FloatField(verbose_name='Lng местоположение'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя рекламного места'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to='advertising.advertisingtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='zoom',
            field=models.FloatField(verbose_name='Зум'),
        ),
        migrations.AlterField(
            model_name='advertisingrent',
            name='advertising',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='advertising.advertising', verbose_name='Рекламное место'),
        ),
        migrations.AlterField(
            model_name='advertisingrent',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата оканчание'),
        ),
        migrations.AlterField(
            model_name='advertisingrent',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Имя организация'),
        ),
        migrations.AlterField(
            model_name='advertisingrent',
            name='start_time',
            field=models.DateTimeField(verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='advertisingtype',
            name='color',
            field=models.CharField(blank=True, default='#0077c2', max_length=10, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='advertisingtype',
            name='icon_text',
            field=models.CharField(blank=True, default='apartment', max_length=255, null=True, verbose_name='Иконка Material Icons'),
        ),
        migrations.AlterField(
            model_name='advertisingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
