# Generated by Django 4.0 on 2022-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_alter_advertising_lat_alter_advertising_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
