# Generated by Django 4.0 on 2022-01-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_alter_advertising_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingtype',
            name='icon',
        ),
        migrations.AddField(
            model_name='advertisingtype',
            name='color',
            field=models.CharField(blank=True, default='#0077c2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advertisingtype',
            name='icon_text',
            field=models.CharField(blank=True, default='apartment', max_length=255, null=True),
        ),
    ]
