# Generated by Django 4.0 on 2022-01-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_remove_advertisingtype_icon_advertisingtype_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('advertising', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='advertising.advertising')),
            ],
        ),
    ]
