# Generated by Django 4.0.1 on 2022-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_alter_advertisingimages_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='advertising',
            name='flows',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='address',
            field=models.ManyToManyField(blank=True, to='advertising.NearPlace'),
        ),
    ]
