# Generated by Django 4.0.1 on 2022-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0008_nearplace_advertising_flows_alter_advertising_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
