# Generated by Django 4.0.1 on 2022-02-12 16:55

import advertising.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0010_alter_advertising_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='address',
        ),
        migrations.AddField(
            model_name='advertising',
            name='address',
            field=models.TextField(blank=True, verbose_name=advertising.models.NearPlace),
        ),
    ]
