# Generated by Django 4.0.1 on 2022-02-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0011_remove_advertising_address_advertising_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingrent',
            name='advertising',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='advertising.advertising'),
        ),
    ]
