# Generated by Django 4.0.1 on 2022-02-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('desription', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('zoom', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='#0077c2', max_length=10, null=True)),
                ('icon_text', models.CharField(blank=True, default='apartment', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Тип место',
                'verbose_name_plural': 'Типы местов',
            },
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place-images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
            options={
                'verbose_name': 'Фото месты',
                'verbose_name_plural': 'Фотки местов',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='place.placetype'),
        ),
    ]
