# Generated by Django 4.0 on 2022-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='color',
            field=models.CharField(blank=True, default='#0077c2', max_length=10, null=True),
        ),
    ]
