# Generated by Django 4.0 on 2022-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_placetype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetype',
            name='icon',
        ),
        migrations.AddField(
            model_name='placetype',
            name='icon_text',
            field=models.CharField(blank=True, default='where_to_vote', max_length=255, null=True),
        ),
    ]
