# Generated by Django 4.0 on 2022-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_remove_placetype_icon_placetype_icon_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='icon_text',
            field=models.CharField(blank=True, default='apartment', max_length=255, null=True),
        ),
    ]
